### ISSUE TITLE
Refactor constantize to use a constant

### ISSUE THREAD

**Issue by dkubb** [mbj/inflecto#1]
@mbj what do you think about this refactoring:

``` ruby
# Provides args for const_get and const_defined? to make them behave
# consistently across different versions of ruby
EXTRA_CONST_ARGS = (RUBY_VERSION < '1.9' ? [] : [ false ]).freeze

# ...

def self.constantize(input)
  names = input.split('::')
  names.shift if names.empty? || names.first.empty?

  names.inject(Object) do |constant, name|
    if constant.const_defined?(name, *EXTRA_CONST_ARGS)
      constant.const_get(name)
    else
      constant.const_missing(name)
    end
  end
end
```

Also, I do wonder about `names.empty? || names.first.empty?`. If `names` is empty, then shifting from it will be a noop. It makes more sense to just check the first argument and shift if it's empty.

**Comment by abinoam** [comment]
Hi @mbj and @dkubb,

I think this issue was rediscussed at #6.
And @Ptico opened PR #7 which is already merged.

The particular line that affects #constantize in PR #7 is https://github.com/mbj/inflecto/pull/7/files#diff-860dbbc3093adb17d781b7cc73a9bc08R118

Can you close this one?
