### ISSUE TITLE
Address is "singularized" to Addres

### ISSUE THREAD

**Issue by fuelxc** [mbj/inflecto#16]
I use the following to outwit:
```
Inflecto.inflections do |inflect|
  inflect.plural  /^(.*address)$/i, '\1es'
  inflect.singular  /^(.*address)(es)?$/i, '\1'
end
```

**Comment by abinoam** [comment]
Hi @fuelxc, could you confirm this issue?
What version of Inflecto are you using? (```Gem::Specification.find_by_name("inflecto").version```)

I've just tested it in my machine and it seems to work fine.

```ruby
require 'inflecto'
# => true
Inflecto.singularize('Addresses')
# => "Address"
Gem::Specification.find_by_name("inflecto").version
# => #<Gem::Version "0.0.2">
```

If unconfirmed, could we close this @mbj ?

**Comment by fuelxc** [comment]
`[1] pry(main)> Inflecto.singularize('Address')
=> "Addres"
[2] pry(main)> Gem::Specification.find_by_name("inflecto").version
=> Gem::Version.new("0.0.2")
[3] pry(main)> 
`

**Comment by fuelxc** [comment]
As a note, it seems to affect any singular item that ends in an s
```
 pry(main)> Inflecto.singularize('mess')
=> "mes"
 pry(main)> Inflecto.singularize('gas')
=> "ga"
```

**Comment by mbj** [comment]
Sorry, I've literally no time to maintain this library as I do not use it for any of my clients / projects right now.

My opensource time is negative for years now. If someone wants to take over feel free to do so.

**Comment by abinoam** [comment]
Hi @fuelxc, sorry, I tested your issue with a typo.
Copying and pasting your last comment worked and I could reproduce the issue.

I'm not a native english speaker, but I think **Address** is already singularized.
I don't think Inflecto as today can detect that "Address" is already singularized and just return it back.
And I also couldn't see how the snippet that you posted can help in treating that case.
Can you confirm that?

**Comment by fuelxc** [comment]
@abinoam it is singular and it can't, that is the defect.  It detects an s at the end of a word and assumes it is plural.  the snippet above works because it can detect if it is already singular by matching the singular form and the pluralization ending once or none (?) and returning the first match which is the singular version

**Comment by abinoam** [comment]
@fuelxc would you mind to reopen this issue at https://github.com/Ptico/inflecto/issues ?
(no need to copy the whole discussion, just link to this one).

We have forked and we are planing a new release.
See #10 for details.

**Comment by abinoam** [comment]
Hi @fuelxc, It's fixed at this PR https://github.com/Ptico/inflecto/pull/2

**Comment by abinoam** [comment]
@fuelxc, could you close this issue?
