### ISSUE TITLE
Support for lower camel case

### ISSUE THREAD

**Issue by pabloh** [mbj/inflecto#17]
`inflecto` lacks support for lower case camel case conversion like [AS has](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/inflector/methods.rb#L52), this would useful to have when generating strings for JSON attributes names.

```ruby
Inflecto.lower_camelize("first_name") # => "firstName"
Inflecto.lower_camelize("name") # => "name"

# Or maybe:

Inflecto.camelize("first_name", lower: true) # => "firstName"
Inflecto.camelize("name", lower: true) # => "name"
```

**Comment by abinoam** [comment]
Hi @pabloh,

Do you mind reopening this issue at https://github.com/Ptico/inflecto/issues ?

**Comment by abinoam** [comment]
@pabloh  you can close this, moved to https://github.com/Ptico/inflecto/issues/3

Let's let the inflecto house clean!
