### ISSUE TITLE
Licence missing in the rubygems version and in the gemspec

### ISSUE THREAD

**Issue by mensfeld** [mbj/inflecto#19]
The "inflecto" gem seems not to have a license at all. Unless a license that specifies otherwise is included, nobody else can use, copy, distribute, or modify that library without being at risk of take-downs, shake-downs, or litigation.

I know, that this gem has a license on github, however it's missing one at rubygems and in a gemspec.

**Comment by josephpage** [comment]
Hey,
Seems fixed for 4 years, see this commit: https://github.com/mbj/inflecto/commit/424d8ff86b6330be4bf653462819948b6af3501f
The problem is that no new versions have been published since January 2013.

**Comment by mensfeld** [comment]
@josephpage I know that it's there in the github sources. Maybe a small release to cover that issue wouldn't be such a bad idea?

**Comment by mbj** [comment]
I'm not confident to release a version as I've never used this code for ages. It was once extracted from AS and DM-1 to support [mutant](https://github.com/mbj/mutant), but I never used it after mutant evolved past it.

I do not have much time for OSS these days. And this gem is by far not a priority to work on. OSS is simply no business model and I've to earn a living. Sorry. I doubt anything will happen any time soon.

**Comment by mbj** [comment]
Sorry, I did not mean to close the issue, wrong button.

**Comment by mensfeld** [comment]
@josephpage  @mbj  thank you for your reply. In that case, maybe it would be possible for you to just ping somehow Rubygems guys to just update the license in their DB. I don't think this should be a big problem.

**Comment by abinoam** [comment]
Hi @mensfeld,

@Ptico and I have forked Inflecto. See discussion at #10.
The repo is at https://github.com/Ptico/inflecto

So, expect to see a release soon. With a license indicated at the gemspec.
If @mbj is not going to release a new gem with the license, and the license is already indicated at the sources, I think we could close this issue. Could we?

**Comment by mensfeld** [comment]
@abinoam great :) I'm closing this one and if nothing changes in 3 months, will reopen :D

**Comment by mensfeld** [comment]
@abinoam stll no release :(

**Comment by Ptico** [comment]
![1](https://user-images.githubusercontent.com/69933/36599471-25470844-18b8-11e8-9994-d2f02ccf2331.png)

**Comment by Ptico** [comment]
![2](https://user-images.githubusercontent.com/69933/36599510-400728ee-18b8-11e8-9f46-13b331f8bfb6.png)

**Comment by Ptico** [comment]
![3](https://user-images.githubusercontent.com/69933/36599518-473a99c0-18b8-11e8-9841-462ecf3d3dee.png)

**Comment by Ptico** [comment]
Hi @mensfeld , speaking seriously, we merged all the efforts to https://github.com/dry-rb/dry-inflector and v0.1.1 is available for use

**Comment by mbj** [comment]
@Ptico Do you mind to PR the "death PR" to this repo? Just leaving a README.md behind explaining where the code is gone?

**Comment by Ptico** [comment]
@mbj yep

**Comment by mensfeld** [comment]
@Ptico thanks. I already use the dry one. Will now have to ping my dependency gems owners to upgrade :D
