### ISSUE TITLE
Restore 1.8 support

### ISSUE THREAD

**Issue by Ptico** [mbj/inflecto#9]
De-facto, inflecto works with 1.8 and the only problem we have is a devtools.

I think it is possible to change Gemfile and travis.yml to have full metrics for >=1.9 and just run `bundle exec rspec` for 1.8.

/cc @tokengeek

**Comment by mbj** [comment]
@Ptico The only option is to drop devtools for 1.8. I intentionally not support 1.8 in devtools. I do not think we should feed dead ecosystems (ruby 1.8) with libraries unless there is a VERY good reason.

**Comment by tokengeek** [comment]
`fog` is planning to drop 1.8.7 (and 1.9.2) support in the next major release we are currently working on. So supporting it is not really a priority for us any more.

We are working around it with specifying the dependency which for the short term is acceptable.

**Comment by Ptico** [comment]
Cool!
